// arc-contracts — shared types for the Story Queue pipeline.

export type Column = "backlog" | "queued" | "in_progress" | "review" | "done";
export type Priority = "high" | "med" | "low";
export type Size = "S" | "M" | "L" | "XL";
export type WorkType = "story" | "bug" | "slice";
export type TaskClass = "feature" | "bugfix" | "migration" | "refactor" | "perf" | "docs";
export type Severity = "S1" | "S2" | "S3" | "S4";

export type RouteId =
  | "codex-explore"
  | "composer-explore"
  | "opus-explore"
  | "composer-implement"
  | "codex-implement"
  | "opus-implement"
  | "codex-check"
  | "composer-check"
  | "opus-check"
  | "fable";

export type AnnotateOutcome = "accepted" | "rejected" | "blocked" | "verification-failed" | "escalated";
export type RunOutcome = AnnotateOutcome | "unrated";

export type Access = "read-only" | "write" | "parent";

export interface Route {
  id: RouteId;
  backend: string;   // "Codex CLI" | "Cursor Agent" | "Claude Agent" | "Claude Code"
  model: string;     // resolved model id
  access: Access;
}

export interface GherkinScenario {
  name: string;
  steps: Array<["Given" | "When" | "Then" | "And", string]>;
}

/** arc-planning-work output: the execution plan a worker runs against. */
export interface Plan {
  tasks: string[];
  files: Array<{ path: string; change: string }>;
  testStrategy: string;
  acMapping: Array<{ ac: string; by: string }>;
}

/** Bug intake fields (arc-bug-finder). */
export interface BugDetail {
  severity: Severity;
  area: string;
  steps: string[];
  rootCause: string;      // "file:line — why"
  fixOptions: string[];   // recommended first
}

/** PRD slice fields (arc-prd-to-issues). */
export interface SliceDetail {
  afk: boolean;                 // false => needs a human decision (HITL)
  blockedBy: string | null;
  userStoriesCovered: string;
}

export interface Story {
  id: string;
  wid: string;                  // "W-000001"
  type: WorkType;
  title: string;
  repo: string;                 // "acme/api"
  branch: string;
  worktree: string;             // "../wt/<slug>"
  column: Column;
  priority: Priority;
  size: Size;
  epic: string;
  taskClass: TaskClass;
  tags: string[];
  description: string;
  criteria: string[];
  scenarios?: GherkinScenario[];
  draft: boolean;               // true = potential issue, not yet filed
  fileRequested?: boolean;      // user asked Fable to file this draft to GitHub
  issue?: string | null;        // "#215" once filed through Fable
  pr?: string | null;
  prState?: "open" | "merged" | "closed";
  annotation?: AnnotateOutcome;
  plan?: Plan | null;
  bug?: BugDetail;
  slice?: SliceDetail;
}

/** Worker -> parent structured handoff (the compact result Fable evaluates). */
export interface Handoff {
  status: "completed" | "blocked" | "failed";
  summary: string;
  changes: string[];
  verification: string[];
  risks: string[];
  next_actions: string[];
}

/** One trace record per delegated run (observability). */
export interface RunRecord {
  id: string;
  storyId: string;
  label: string;
  repo: string;
  route: RouteId;
  backend: string;
  model: string;
  access: Access;
  tokens: number;
  durMs: number;
  status: "completed" | "failed";
  changed: number;              // files changed
  outcome: RunOutcome;
}

/** An attached, already-running agent session = a project. */
export interface Project {
  id: string;
  repo: string;
  path: string;                 // session cwd
  branch: string;
  model: string;
  pid: number;
  worktreeRoot: string;
  status: "attached" | "detached";
}

/** Parallelism law enforced by the queue manager. */
export const PARALLELISM = {
  readOnlyRunsInParallel: true,           // explore/check/review never lock
  writeSerializesPerWorktree: true,       // advisory lock keyed by worktree
  separateWorktreesParallelizeWrites: true
} as const;

export type IntakeKind = "feature" | "prd" | "bug";
export interface IntakeItem {
  id: string;
  kind: IntakeKind;
  title: string;
  description: string;
  status: "pending" | "claimed" | "done";
  storyId?: string | null;   // set when intake.complete drafts a story
}

export type IntakeDraftSource = "model" | "fallback";

/** A selectable intake proposal generated by Fable/the harness or the fallback. */
export interface IntakeDraftProposal {
  include: boolean;
  type: WorkType;
  title: string;
  priority: Priority;
  size: Size;
  summary: string;
  description: string;
  epic: string;
  taskClass: TaskClass;
  tags?: string[];
  criteria: string[];
  scenarios?: GherkinScenario[];
  bug?: BugDetail;
  slice?: SliceDetail;
}

export interface IntakeGenerateResult {
  source: IntakeDraftSource;
  exploreNote: string;
  drafts: IntakeDraftProposal[];
}

/** Persisted daemon config (Orchestrator view controls). */
export interface AppConfig {
  autoRun: boolean;
  maxParallel: number;
}

/** Full drawer hydration: the story plus its persisted runs + handoff. */
export interface StoryDetail {
  story: Story;
  runs: RunRecord[];
  handoff: Handoff | null;
}
